---
title: "covid_3_27_reanalysis"
author: "Nicholas Nagle"
date: "3/27/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(sf)
library(tidyverse)
library(rstan)
library(tidybayes)
library(purrr)
```

```{r data proc, echo=FALSE, message=FALSE, warning=FALSE}

geodf <- readr::read_rds('../data/washington-acs.RData')
# Create a unique metro_id
geodf <- geodf %>% 
  mutate(metro_fact = fct_explicit_na(as.factor(csa_title),'non-metro'),
         metro_id = as.numeric(metro_fact),
         county_fact = as.factor(geoid),
         county_id = as.numeric(county_fact))

coviddf <- read_csv("../data/washington-covid19.csv")
# Tasks: convert the date to numeric
coviddf <- coviddf %>%
  mutate(geoid = as.character(geoid), 
         date_r = 1 + as.numeric(date) - min(as.numeric(date))) %>%
  left_join(geodf %>% select(geoid,county_fact, county_id), by=c('geoid')) 


covariate_df <- geodf %>% select(acs_median_income_e)
response_df <- coviddf %>%
  select(county_id, date_r, new_cases) %>%
  pivot_wider(names_from = date_r, values_from = new_cases, names_prefix = 'day_',
              values_fill = list(new_cases=0))

# Get a list of counties with >50 cases
big_counties <- rowSums(response_df)>50
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
csvfiles <- list.files('../tmp/', pattern='samples_nbh_grw_[0-9].csv', full.names=TRUE)
#stan_fit <- read_stan_csv(paste0('../tmp/', csvfiles))
#read_stan_csv doesn't work properly??

warmup <- 500

stan_dat <- tibble(file=csvfiles, .chain=1:length(csvfiles)) %>% 
  group_by(file) %>% nest() %>%
  mutate(samples = map(.x=file, ~read_csv(.x, comment='#'))) %>%
  mutate(samples = map(.x=samples, ~mutate(.x,.iteration=1:n() ))) %>%
  unnest(cols=data) %>%
  unnest(cols=samples) %>%
  ungroup()  %>%
  mutate(.draw=1:n()) %>%
  select(.draw, .chain, .iteration, everything()) 

```




# Plot growth rates in log- space

Only plotting counties with greater than 50 cases total.

```{r, echo=FALSE}
sample_lambda <- stan_dat %>% 
  select(.draw, .chain, .iteration, starts_with("log_lambda")) %>%
  pivot_longer( cols=starts_with("log_lambda"), names_to='.variable', values_to=".value" ) %>%
  separate(.variable, into=c('.variable','i','t'), sep='\\.') %>%
  mutate(i=as.numeric(i), t=as.numeric(t))
```

```{r, echo=FALSE}
test_draws <- c(968,802,692,764,534,904,893,768,810,815)
plot_df <- sample_lambda %>% 
  filter(.iteration > warmup) %>%
  group_by(.chain, .iteration) %>%
  nest() %>%
  ungroup() %>%
  #filter(.draw %in% test_draws) %>%
  sample_n(10)   %>%
  unnest(cols=data) %>%
  left_join(geodf %>% 
              st_drop_geometry() %>% 
              select(county_id, county_name),
            by=c('i'='county_id'))  %>%
  left_join(coviddf %>% select(date, date_r) %>% unique, by=c('t'='date_r'))

  
plot_df %>% filter(i %in% which(big_counties)) %>%
  ggplot(aes(x=date,y=exp(.value)*100000, group=.draw)) +
  geom_line(alpha = 1/4, color = "#08519C") +
  facet_wrap(~county_name) + 
  scale_y_log10() +
  ylab('new cases per 100,000 persons')
```

```{r}
plot_df %>% filter(county_name=='King') %>%
  ggplot(aes(x=date,y=exp(.value)*100000, group=.draw)) +
  geom_line(alpha = 1/4, color = "#08519C") +
  facet_wrap(~county_name) + 
  scale_y_log10() +
  facet_wrap(~.draw) +
  ylab('new cases per 100,000 persons')
```





```{r, echo=FALSE}
plot_df <- sample_lambda %>% 
  filter(.iteration > warmup) %>%
  group_by(i,t) %>%
  summarize(mean = mean(.value),
            q05 = quantile(.value, .05),
            q95 = quantile(.value, .95)) %>%
  ungroup()  %>%
  left_join(geodf %>% 
              st_drop_geometry() %>% 
              select(county_id, county_name),
            by=c('i'='county_id')) %>%
  left_join(coviddf %>% select(date, date_r) %>% unique, by=c('t'='date_r'))

plot_df %>%
  filter(i %in% which(big_counties)) %>%
  ggplot(aes(x=date, y=exp(mean)*100000)) +
  geom_line() +
  geom_ribbon( aes( ymin=exp(q05)*100000 , ymax=exp(q95)*100000 ) ,
               alpha=.5)+
  scale_y_log10() +
  facet_wrap(~county_name) + 
  ylab('new cases per 100,000 persons')
```


```{r}
plot_df %>%
  filter(i %in% which(big_counties)) %>%
  ggplot(aes(x=date, y=exp(mean)*100000, color=county_name)) +
  geom_line()+
  scale_y_log10() +
  ylab('new cases per 100,000 persons') + 
  scale_color_discrete('County')
  
```

# Plot posterior probability of changing slope
```{r, echo=FALSE}
sampleb <- stan_dat %>% select(.draw, .chain, .iteration, starts_with("b0.")) %>%
  pivot_longer( cols=starts_with("b0."), names_to='.variable', values_to=".value" ) %>%
  separate(.variable, into=c('.variable','i','t'), sep='\\.') %>%
  mutate(i=as.numeric(i), t=as.numeric(t))


plot_df <- sampleb %>% group_by(i,.chain, .iteration) %>%
  filter(.iteration > warmup) %>%
  arrange(t) %>%
  mutate(diff1 = .value-lag(.value,1),
         diff2 = .value-lag(.value,2),
         diff3 = .value-lag(.value,3),
         diff4 = .value-lag(.value,4),
         diff5 = .value-lag(.value,5),
         diff6 = .value-lag(.value,6),
         diff7 = .value-lag(.value,7)) %>%
  ungroup() %>%
  filter(t==31)   %>%
  select(-.value) %>%
  pivot_longer(cols = starts_with('diff'),
               names_to='lag',
               names_prefix='diff',
               values_to = 'value' ) %>%
  mutate(variable=lag, i = as.integer(i)) %>%
  left_join(geodf %>% st_drop_geometry() %>% select(county_id, county_name),
            by=c('i'='county_id')) 
```


```{r, echo=FALSE}
ggplot(plot_df %>% filter(i<=20), aes(y=exp(value), x=lag)) + 
  stat_dots(quantiles=20) + 
  #stat_eye() +
  facet_wrap(~county_name) + 
  geom_hline(aes(yintercept=1), color='grey25') +
  ylab('change in rate (multiplicative scale)') +
  xlab('days before March 25') + 
  ggtitle('Probability of changing rate in last X days\nReference=March 25')
```

```{r, echo=FALSE}
ggplot(plot_df %>% filter(i>20), aes(y=exp(value), x=lag)) + 
  stat_dots(quantiles=20) + 
  #stat_eye() +
  facet_wrap(~county_name) + 
  geom_hline(aes(yintercept=1), color='grey25') +
  ylab('change in rate (multiplicative scale)') +
  xlab('days before March 25') + 
  ggtitle('Probability of changing rate in last X days\nReference=March 25')
```



```{r}
sample_b0_raw <- stan_dat %>% 
  select(.draw, .chain, .iteration, starts_with("b0_raw")) %>%
  pivot_longer( cols=starts_with("b0_raw"), names_to='.variable', values_to=".value" ) %>%
  separate(.variable, into=c('.variable','i','t'), sep='\\.') %>%
  mutate(i=as.numeric(i), t=as.numeric(t)) %>%  
  left_join(geodf %>% st_drop_geometry() %>% select(county_id, county_name),
            by=c('i'='county_id')) %>%
  filter(county_name=='King', .draw ==672)
  
```

```{r}
ggplot(sample_b0_raw, aes(x=t,y=.value)) + geom_line() 
```

```{r}
sample_b0 <- stan_dat %>% 
  select(.draw, .chain, .iteration, starts_with("b0.")) %>%
  pivot_longer( cols=starts_with("b0."), names_to='.variable', values_to=".value" ) %>%
  separate(.variable, into=c('.variable','i','t'), sep='\\.') %>%
  mutate(i=as.numeric(i), t=as.numeric(t)) %>%  
  left_join(geodf %>% st_drop_geometry() %>% select(county_id, county_name),
            by=c('i'='county_id')) %>%
  filter(county_name=='King', .draw ==672)
  
```

```{r}
ggplot(sample_b0, aes(x=t,y=.value)) + geom_line() 
```

```{r}
sample_672 <- stan_dat %>%
  filter(.draw==672) %>%
  pivot_longer(cols = 5:8453, names_to='variable',values_to='value') %>%
  separate(variable, into=c('variable','i','t'), sep='\\.', fill='right') %>%
  mutate(i=as.numeric(i), t=as.numeric(t)) %>%
  left_join(geodf %>% st_drop_geometry() %>% select(county_id, county_name),
            by=c('i'='county_id')) %>%
  filter(county_name=='King')

sample_672_t <- sample_672 %>%
  select(-.draw, -.chain, -.iteration, -file, -i, -county_name) %>%
  filter(!is.na(t))   %>% 
  pivot_wider(id_cols=c('t'), names_from=variable, values_from=value) %>%
  mutate(b0_lam = b0_raw * horse_lambda_tilde) %>%
  pivot_longer(-t, names_to='variable', values_to='value')
  
```

```{r}
ggplot(sample_672_t %>% filter(!is.na(t)), aes(x=t, y=value)) + 
  geom_line() +
  facet_wrap(~variable, scales='free_y')
```
